name: '[QE] Cypress Runner'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Choose another branch to test'
        required: true
        default: master
  pull_request:
    branches:
      - master
      - main
    types: 
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore: 
      - docs/**
      - README.md     
      - CHANGELOG.md

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Check system resources and Chrome version
        run: |
          nproc
          free -m
          chrome --version

      - name: Checkout App
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get Cypress Runner
        run: git clone https://github.com/vtex-apps/cy-runner.git

      - name: Cache
        uses: actions/cache@v2
        with:
          path: '~/.cache/'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Cypress
        run: |
          yarn install --frozen-lockfile
          git checkout feature/add-parallelization
          rm -rf .git
        working-directory: ./cy-runner

      - name: Run Cypress Runner
        run: yarn cy-r
        env:
          VTEX_QE: ${{ secrets.VTEX_QE }}
          DEBUG: cypress:server:util:process_profiler
          #NODE_NO_WARNINGS: 1          
          #ELECTRON_RUN_AS_NODE: 1

      - name: Save results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: cy-runner-logs
          path: cy-runner/logs
